name: Build Command Blocker
# Builds the project and archives the checkstyle results

on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE.txt'
      - 'CONTRIBUTING.md'
  workflow_dispatch:
    inputs:
      release:
        description: Publish a Release
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build the Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Check gradle validation
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace

      - name: Setup Environment Variables
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version >> $GITHUB_ENV

      - name: Archives Results
        uses: actions/upload-artifact@v3
        with:
          name: CommandBlocker-${{ env.mod_version }}
          path: |
            build/reports/
            **/build/reports/
            **/build/libs/CommandBlocker-*-*.jar

      - name: Release Version to GitHub
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.release }}
        with:
          body_path: ${{ github.workspace }}/build/CHANGELOG.md
          tag_name: ${{ env.mod_version }}
          name: Command Blocker v${{ env.mod_version }}
          target_commitish: ${{ github.sha }}
          files: |
            **/build/libs/CommandBlocker-*-*.jar
            **/build/libs/CommandBlocker-*-*.jar
